#!/usr/bin/env python3
"""Build the challenge-1 submission FASTA by READING each sequence out of its source CSV.

NEW FILE 2026-10-06. Local, no compute cost. Refuses an existing --out.

⛔⛔ WHY IT READS RATHER THAN EMBEDS. A submission is the one artefact where a single transcription
slip is unrecoverable and invisible: a wrong residue still looks like a protein. So no sequence is
typed into this file. Each is read from the CSV that the scoring pipeline itself read, and the
script ASSERTS the expected length and the expected first/last residues before writing anything.

⛔ SUPERSEDED FOR THE DEPOSITED FASTA, 2026-10-06. This script built an earlier FOUR-sequence
file, which is not deposited. The deposited `submitted_sequences.fasta` is generated by
`make_deposit_fasta.py` and holds TEN sequences, with `id15` dropped and `id86`
added. See `SEQUENCE_SET_CORRECTION_20261006.md`. This file is kept as the record of how the
earlier four were read out of their source CSVs.

TARGET, settled 2026-10-06: challenge 1 is the **monomeric tethered EGFR ectodomain**
(human Met 1-Ser 645 = mature 1-621, mouse Met 1-Ser 647). The trimeric target in
The trimeric target belongs to the NEXT challenge. ⇒ these four designs are the right
target; the pH / mouse / R1-R4 chain is not cited here.

ORDER IS THE RANKING, best first, so the file can be TRUNCATED from the bottom if the organizers
cap the count (no cap was on record at the time of writing).

Run: <a python that carries biotite> scripts/build_submission_fasta.py --out <fresh>.fasta
"""
import argparse, csv, os, sys

LS = os.environ.get("DESIGN_DATA_ROOT")
if not LS:
    sys.exit("⛔ $DESIGN_DATA_ROOT unset. Point it at a directory holding the two campaign "
             "label CSVs named below.\n"
             "⛔ Those CSVs are NOT part of this deposit, so this script cannot be re-run "
             "from the deposit alone. The sequences it produced are deposited directly, as "
             "submitted_sequences.fasta and submission_challenge1_20261006.csv.")

BRIDGE = f"{LS}/egfrBR50_c1_land_20261005/label_BR_0046_chosen_POOLED100.csv"
A1 = f"{LS}/egfrA1_20261004"

# (rank, id, arm, source csv, id column, expected length, expected first+last residue, note)
WANT = [
    (1, "85",   "bridge", BRIDGE,              "seq",    145, ("S", "A"),
     "bridge: full_both 20/24 at depth; engages BOTH footprints (11/11 site A AND 7/7 FP7'); "
     "backbone arm_shard11_shard11_41_model_5"),
    (2, "2015", "siteA",  f"{A1}/training_c3.csv", "seq_id", 75, ("G", "A"),
     "site A: highest site-A deep label in the programme, 0.857 over 70 draws, fold rate 1.000; "
     "backbone arm_shard11_shard11_24_model_2"),
    (3, "15",   "siteA",  f"{A1}/training_c1.csv", "seq_id", 75, ("G", "S"),
     "site A: 25 of 75 residues from rank 2 -- the real diversity axis; deep 0.779, lowest sd "
     "0.038; WARNING full_A only 0.178"),
    (4, "89",   "siteA",  f"{A1}/training_c1.csv", "seq_id", 75, ("G", "A"),
     "site A: 17 of 75 from rank 2; W10 co-winner, 6/10 draws full epitope + fold; "
     "WARNING only 10 draws, never deep-tested"),
]


def load(path, idcol, sid):
    if not os.path.exists(path):
        sys.exit(f"⛔ source missing: {path}")
    for r in csv.DictReader(open(path)):
        if str(r.get(idcol, "")).lstrip("id") == sid:
            seq = r.get("sequence")
            if not seq:
                sys.exit(f"⛔ {path}: row id{sid} has no 'sequence' column")
            return seq.strip().upper()
    sys.exit(f"⛔ {path}: no row with {idcol} == id{sid}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--limit", type=int, default=0,
                    help="write only the top N (the organizers' cap, if one is ever stated)")
    a = ap.parse_args()
    if os.path.exists(a.out):
        sys.exit(f"⛔ --out exists: {a.out}. Fresh --out.")

    recs, aas = [], set("ACDEFGHIKLMNPQRSTVWY")
    for rank, sid, arm, src, idcol, exp_len, exp_ends, note in WANT:
        seq = load(src, idcol, sid)
        if len(seq) != exp_len:
            sys.exit(f"⛔ id{sid}: length {len(seq)}, expected {exp_len}. Refusing.")
        if (seq[0], seq[-1]) != exp_ends:
            sys.exit(f"⛔ id{sid}: ends {seq[0]}..{seq[-1]}, expected "
                     f"{exp_ends[0]}..{exp_ends[1]}. Refusing.")
        bad = sorted(set(seq) - aas)
        if bad:
            sys.exit(f"⛔ id{sid}: non-standard residues {bad}. Refusing.")
        recs.append((rank, sid, arm, seq, os.path.basename(src), note))

    seqs = {r[3] for r in recs}
    if len(seqs) != len(recs):
        sys.exit("⛔ duplicate sequences in the set. Refusing -- a duplicate wastes a slot.")

    # the diversity claim the ranking rests on, recomputed here so the FASTA cannot disagree with it
    sa = [r for r in recs if r[2] == "siteA"]
    pw = {}
    for i in range(len(sa)):
        for j in range(i + 1, len(sa)):
            if len(sa[i][3]) == len(sa[j][3]):
                pw[(sa[i][1], sa[j][1])] = sum(x != y for x, y in zip(sa[i][3], sa[j][3]))

    out = recs if not a.limit else recs[:a.limit]
    with open(a.out, "w") as fh:
        for rank, sid, arm, seq, src, note in out:
            fh.write(f">egfr_{arm}_id{sid} rank={rank} len={len(seq)} src={src} | {note}\n")
            for k in range(0, len(seq), 60):
                fh.write(seq[k:k + 60] + "\n")

    print(f"wrote {a.out}: {len(out)} sequences")
    for rank, sid, arm, seq, src, _n in out:
        print(f"   rank {rank}  {arm:6s} id{sid:<5s} {len(seq)} aa   read from {src}")
    print("   ✅ every length and both terminal residues asserted; no sequence typed into the script")
    if pw:
        print("   site-A pairwise Hamming (recomputed from what was written):")
        for (x, y), d in sorted(pw.items(), key=lambda t: -t[1]):
            print(f"      id{x} vs id{y}: {d} of 75")
    print("   ⚠️ NO submission-count cap is on record; truncate with --limit if one is stated.")
    print("   ⚠️ This script does not run the novelty check (organizer FAQ item 5);")
    print("      see NOVELTY_MEASURED_20261006.md for that measurement.")


if __name__ == "__main__":
    main()
