"""WT -> RFd3-output residue mapping, loaded from the map the BUNDLE ships.

⛔⛔ WHY A MODULE AND NOT A CONSTANT (2026-10-02). Every scorer on this project carried a
CONSTANT offset (`W2O=-369`, `A2O=-3`, `anchor=(409-369)`) because the generation target was a
CONTIGUOUS crop. The sphere targets are NOT contiguous -- site A is 15 segments, site B is 26 --
and RFd3 renumbers the target 1..N, discarding every gap. **No constant offset exists.**
A constant is not merely imprecise here, it silently reads a different residue: WT H409 is
output B141, while `409-369` reads B40, which is a CYS.

⭐ The map is generated by `make_wt2out_map.py` and shipped INSIDE the bundle beside the target
it describes (`WT2OUT_siteA.tsv` / `WT2OUT_siteB.tsv`), so a design can never be scored against
a map for a different cut. It was VERIFIED against real RFd3 output on both sites by residue-type
identity (site A 231/231, site B 230/230).
⛔ TARGET is chain B in RFd3 output; BINDER is chain A. (Opposite to RFd2.)
"""
import os


class WT2Out:
    def __init__(self, path):
        self.path = path
        self.w2o, self.o2w, self.resname, self.seg = {}, {}, {}, {}
        with open(path) as fh:
            for l in fh:
                if l.startswith("#") or l.startswith("wt_resnum"):
                    continue
                wt, out, rn, sg = l.split()
                wt, out, sg = int(wt), int(out), int(sg)
                self.w2o[wt] = out
                self.o2w[out] = wt
                self.resname[wt] = rn
                self.seg[wt] = sg
        if not self.w2o:
            raise SystemExit(f"⛔ {path} holds no mapping rows")
        self.nseg = max(self.seg.values()) + 1

    def __len__(self):
        return len(self.w2o)

    def out(self, wt):
        """output chain-B residue number for a WT residue. ⛔ Refuses rather than guessing."""
        try:
            return self.w2o[wt]
        except KeyError:
            raise SystemExit(f"⛔ WT {wt} is NOT in {os.path.basename(self.path)} -- it is "
                             f"outside this sphere cut, so no design was built against it. "
                             f"Map covers {len(self.w2o)} residues in {self.nseg} segments.")

    def type_of(self, wt):
        return self.resname[wt]

    def check_target(self, out_res, path="?"):
        """⛔⛔ THE CHECK THAT DOES NOT DEPEND ON LUCK. Assert EVERY target residue type.

        `out_res` = [(out_resid, resname3)] for the design's target chain (chain B), any order.

        An ANCHOR-ONLY assertion is not enough and this is measured, not theoretical: site B's
        retired constant offset (out = WT - 3) is accidentally CORRECT for all 8 of its footprint
        residues, because they all fall in the sphere's first segment, which starts at the same
        WT 4 the old 77 aa crop did. So the old offset passes every type check on site B while
        being wrong for the other 203 residues -- "runs clean and lies". A check that cannot
        fail is not a check. Comparing the WHOLE chain removes the luck.
        """
        got = dict(out_res)
        want = {o: self.resname[w] for w, o in self.w2o.items()}
        if len(got) != len(want):
            raise SystemExit(f"⛔ {path}: target chain has {len(got)} residues, map describes "
                             f"{len(want)} ({os.path.basename(self.path)}) -- wrong cut")
        bad = [(o, want[o], got[o]) for o in sorted(want) if got.get(o) != want[o]]
        if bad:
            raise SystemExit(f"⛔ {path}: {len(bad)} of {len(want)} target residue types disagree "
                             f"with {os.path.basename(self.path)} -- this map does NOT describe "
                             f"this design's target. First: out {bad[0][0]} map={bad[0][1]} "
                             f"design={bad[0][2]}")
        return len(want)

    def describe(self):
        return (f"{os.path.basename(self.path)}: {len(self.w2o)} residues, {self.nseg} segments, "
                f"WT {min(self.w2o)}-{max(self.w2o)} -> out 1-{len(self.w2o)}")


def load(path=None, site=None):
    """Resolve the map: explicit path, else $WT2OUT_MAP, else $WT2OUT_MAP_<SITE>."""
    p = path or os.environ.get("WT2OUT_MAP") or \
        (os.environ.get(f"WT2OUT_MAP_{site}") if site else None)
    if not p:
        raise SystemExit("⛔ no WT->output map given. Pass --wt2out <bundle>/WT2OUT_site?.tsv "
                         "(generated by make_wt2out_map.py). ⛔ There is NO constant offset for a "
                         "sphere-cut target -- do not substitute one.")
    if not os.path.exists(p):
        raise SystemExit(f"⛔ WT->output map not found: {p}")
    return WT2Out(p)
